// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpWI_aAaf49CTBkvzk5-QpNGjY7Cm18I',
    appId: '1:428294323885:web:995d57548d3c0020225024',
    messagingSenderId: '428294323885',
    projectId: 'cosmo-care-8ffaa',
    authDomain: 'cosmo-care-8ffaa.firebaseapp.com',
    databaseURL: 'https://cosmo-care-8ffaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosmo-care-8ffaa.appspot.com',
    measurementId: 'G-XQDGE396K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgE2EgaSMcKv8g-kukQ4C3xj2yweY-fko',
    appId: '1:428294323885:android:a65fcda2a703e8ff225024',
    messagingSenderId: '428294323885',
    projectId: 'cosmo-care-8ffaa',
    databaseURL: 'https://cosmo-care-8ffaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosmo-care-8ffaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLOcRQDMO4UngcWU-ui9G5JqdYxSIF1ng',
    appId: '1:428294323885:ios:4042353c49aee0d7225024',
    messagingSenderId: '428294323885',
    projectId: 'cosmo-care-8ffaa',
    databaseURL: 'https://cosmo-care-8ffaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosmo-care-8ffaa.appspot.com',
    iosClientId: '428294323885-o2jt0c6v6u7q5rl9e54b5bt756vj66u6.apps.googleusercontent.com',
    iosBundleId: 'technology.technotown.cosmocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLOcRQDMO4UngcWU-ui9G5JqdYxSIF1ng',
    appId: '1:428294323885:ios:4042353c49aee0d7225024',
    messagingSenderId: '428294323885',
    projectId: 'cosmo-care-8ffaa',
    databaseURL: 'https://cosmo-care-8ffaa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosmo-care-8ffaa.appspot.com',
    iosClientId: '428294323885-o2jt0c6v6u7q5rl9e54b5bt756vj66u6.apps.googleusercontent.com',
    iosBundleId: 'technology.technotown.cosmocare',
  );
}
